doctrine:
  dbal:
    url: "%env(resolve:DATABASE_URL)%"
    server_version: '17'   # uncomment if you want to lock the version
    profiling_collect_backtrace: "%kernel.debug%"
    use_savepoints: true
    profiling: false

  orm:
    auto_generate_proxy_classes: true
    enable_lazy_ghost_objects: true
    default_entity_manager: default
    entity_managers:
      default:
        connection: default
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        dql:
          string_functions:
            match: DoctrineExtensions\Query\Mysql\MatchAgainst
            replace: DoctrineExtensions\Query\Mysql\Replace
        mappings:
          App:
            type: attribute
            is_bundle: false
            dir: "%kernel.project_dir%/src/Entity"
            prefix: 'App\Entity'
            alias: App

when@test:
  doctrine:
    dbal:
      # "TEST_TOKEN" is typically set by ParaTest
      dbname_suffix: "_test%env(default::TEST_TOKEN)%"

when@prod:
  doctrine:
    orm:
      auto_generate_proxy_classes: false
      proxy_dir: "%kernel.build_dir%/doctrine/orm/Proxies"
      query_cache_driver:
        type: pool
        pool: doctrine.system_cache_pool
      result_cache_driver:
        type: pool
        pool: doctrine.result_cache_pool

  framework:
    cache:
      pools:
        doctrine.result_cache_pool:
          adapter: cache.app
        doctrine.system_cache_pool:
          adapter: cache.system
